// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7Tv4eFxBfQlgSPqePebvmEVNW5eg8W4',
    appId: '1:556658927167:web:93b0e1623ed153d5957a8a',
    messagingSenderId: '556658927167',
    projectId: 'pipocou-filmes',
    authDomain: 'pipocou-filmes.firebaseapp.com',
    storageBucket: 'pipocou-filmes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx9LIAXjcAqiUz9YsVohR2a4rdDoOyCEA',
    appId: '1:556658927167:android:3a52a74f68fdba02957a8a',
    messagingSenderId: '556658927167',
    projectId: 'pipocou-filmes',
    storageBucket: 'pipocou-filmes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRp9qmSV6dCV4l2oFMAWt-09E03mHE330',
    appId: '1:556658927167:ios:9003a175639ff652957a8a',
    messagingSenderId: '556658927167',
    projectId: 'pipocou-filmes',
    storageBucket: 'pipocou-filmes.appspot.com',
    androidClientId: '556658927167-penei6h792stf0up6osn30t9sb73js4e.apps.googleusercontent.com',
    iosClientId: '556658927167-sdt038l4t3rb9irh6j0jkmt51kvkn1j5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pipocouFilmes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRp9qmSV6dCV4l2oFMAWt-09E03mHE330',
    appId: '1:556658927167:ios:dda32035a53eab2a957a8a',
    messagingSenderId: '556658927167',
    projectId: 'pipocou-filmes',
    storageBucket: 'pipocou-filmes.appspot.com',
    androidClientId: '556658927167-penei6h792stf0up6osn30t9sb73js4e.apps.googleusercontent.com',
    iosClientId: '556658927167-v48qsm3qcs11s0h59dvqpms6bv519ht0.apps.googleusercontent.com',
    iosBundleId: 'com.example.pipocouFilmes.RunnerTests',
  );
}
